# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

compute_factor_scores_cpp <- function(post_draws, data, lambda_idx, sig_idx, nu_idx, J, M, N, has_missing, obs_patterns) {
    .Call(`_BayesEFA_compute_factor_scores_cpp`, post_draws, data, lambda_idx, sig_idx, nu_idx, J, M, N, has_missing, obs_patterns)
}

rsp_exact_eff <- function(Lambda_tilde, Lambda_star_init, J, M, maxIter, threshold) {
    .Call(`_BayesEFA_rsp_exact_eff`, Lambda_tilde, Lambda_star_init, J, M, maxIter, threshold)
}

